### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by stevygee** [PeterTheOne/epu-accounting#1]
Input:
- [ ] Bank CSV
- [ ] Kreditkartenabrechnung/PDF/CSV
- [ ] PayPal Sheet
- [ ] Rechnung PDF

Interface:
- [ ] Rules mit Klarname/Kommentar/Kategorien/Privat/Steuersatz
- [ ] Kreditkartenabbuchung
- [ ] one time ignore
- [ ] PDF drag and drop
- [ ] Buchungszeilen farbkodiert
- [ ] Kreditkarte/PayPal integrieren in main csv

Output:
- [ ] Sheet mit lfd nummer, Pages/Monat
- [ ] private/business summen/monat
- [ ] graph ein/ausgaben empfänger
- [ ] PDF nummeriert

**Comment by stevygee** [comment]
We should split this up into multiple issues 😅
