### ISSUE TITLE
MVC WIP ToDo

### ISSUE THREAD

**Issue by stevygee** [PeterTheOne/epu-accounting#12]
Model:
  - SQLite
  - csv

Views:
  - CLI
  - GUI
  - WebGUI

- [ ] crud records
- [ ] buttons for import/match/..
- [ ] second tab
- [ ] crud in/out
- [ ] future graph
---
- [ ] persistant data store
- [ ] update data store (hashes?)
---
- [ ] error events
- [ ] model notifies controller -> controller triggers view update
- [ ] use Record model everywhere
